<a href="https://colab.research.google.com/github/Aarchi8824/Exploring-Digital-Technology-OT2-/blob/main/Class2_computationalstats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



> #Introduction to Python



In [ ]:
print('welcome to Python') #this is a print statement

welcome to Python


##Variables and expressions

In [ ]:
a = 5  #this variables stores an int
var1 = 10.0 #stores a float
str_var = "Alex" #this stores a string

In [ ]:
a

5

In [ ]:
var1

10.0

In [ ]:
str_var

'Alex'

In [ ]:
type(a)   #Lists the datatype of the variables

int

In [ ]:
type (var1)

float

In [ ]:
num1 = 1
num2 = 3
num3 = num1/num2 #there is finite precision when it comes to floating point numbers.
num3

0.3333333333333333

In [ ]:
type(num3)

float

In [ ]:
type(str_var)

str

In [ ]:
y = var1 + a #adding an int and a float
y

15.0

##Operators

In [ ]:
p = num1+num2 #addition
q = num1-num2 # Subtraction
r = num1*num2 # Multiplication
s = num1/num2 # Division
t = num1//num2 # Integer division; gives the dividend
u = num1%num2 # this gives the reminder
print(p, q, r, s, t, u)
print("p=", p) # Tp get a perticular value
print(f"p={p}")
print(f"The value of p is",p) #Old-fashioned way of combinig strings and variables

4 -2 3 0.3333333333333333 0 1
p= 4
p=4
The value of p is 4


### lists

In [ ]:
int_list = [1, 2, 3, 4] #List of integers
float_list = [1.0, 2.5, 3.7, 5.5] # List of floats
str_list = ["a", "b", "c", "d"] # List of strings
mixed_list = [1, 2.4, "a", p] # Mized list containing elemets of different types

In [ ]:
mixed_list

[1, 2.4, 'a', 4]

### Aggregate functions on Lists

In [ ]:
sum(int_list) #Gives the sum of all elements

10

In [ ]:
len(float_list) # Gives the count of the number of elements in the list

4

In [ ]:
sum(mixed_list) # Can lead to errors if there are different types of datatypes, so avoid using mixed lists

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [ ]:
sum(str_list)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
int_float_list = int_list + float_list #The + operator when used with lists does concentration
int_float_list

[1, 2, 3, 4, 1.0, 2.5, 3.7, 5.5]

### Exercise

In [ ]:
scores = [65, 78, 30, 85]
average_score = sum(scores)/len(scores)
average_score
max_score = max(scores)
max_score
print(f"average score of this class is", average_score )

average score of this class is 64.5


### Functions and If statements

In [ ]:
def has_student_passed(score):
  """
  This is a multiline comment.
  This function takes the score and returns pass if
  the score is above 40.
  """
  if score >= 40:
    print("The student has passed the course.") # Gets executed when if condition evaluates to true
  else:
    print("The student has not passed the course.") # Gets exectured when if conditon evaluates to false
  return


###  For Loop

In [ ]:
for s in scores:
  print(f"s={s},")
  has_student_passed(s)


s=65,
The student has passed the course.
s=78,
The student has passed the course.
s=30,
The student has not passed the course.
s=85,
The student has passed the course.


##Homework: write a function to calculate grades and return the grade

In [ ]:
#The function will look something like this
def get_grades(score):
  """
  This is a multiline comment.
  This function takes the score and returns pass if
  the score is above 40.
  """
  if score >= 40 and score <=50:
   return "E"
  elif score>50 and score<=60:
    return "D"
  elif score>60 and score<= 100:
    return"A"
    return"U"




## Getting help


In [ ]:
help(sum) # To get help on function definitions


Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers

    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



## Dictionaries

In [ ]:
#A dictionary is a data structure that does 1-1 mapping of key-value pairs
scores_dict = {"Alex":scores[0], "Nandini":scores[1], "Trusha":scores[2], "Mohammed":[3]}
scores_dict


{'Alex': 65, 'Nandini': 78, 'Trusha': 30, 'Mohammed': [3]}

In [ ]:
help(dict)

Help on class dict in module builtins:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |
 |  Built-in subclasses:
 |      StgDict
 |
 |  Methods defined here:
 |
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __gt__(self, value, /)
 |      Return self>va

In [ ]:
scores_dict.keys() # Gives the list of keys in the dictionary

dict_keys(['Alex', 'Nandini', 'Trusha', 'Mohammed'])

In [ ]:
scores_dict.values() #Gives all the values of the dicctionary

dict_values([65, 78, 30, [3]])

### Homework
Use this dictinary along with the for loop to print the name and the
score of the student
You can also try calculating the grade of each student inside the for bloack

In [ ]:
for key, scores in zip(scores_dict.keys(), scores_dict.values()):
  print(key, scores)

Alex 65
Nandini 78
Trusha 30
Mohammed [3]


### NUMPY

In [ ]:
import numpy as np # Importing the numpy package

In [ ]:
zeros_arr = np.zeros(10) # An array of 10 zeros
zeros_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
zeros_arr_int_2D = np.zeros(shape=(4,3),dtype=int) # A 2D array of datatypes pf integer
zeros_arr_int_2D

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
ones_arr = np.ones(10) # An array of 10 ones
ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(f"First array is {arr1} and its type is{type(arr1)}") # arr1 is no longer a simple list; it is a numpy
print(f"Second array is {arr2}")

First array is [1 2 3 4 5] and its type is<class 'numpy.ndarray'>
Second array is [ 6  7  8  9 10]


In [ ]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.



### NUMPY array operations

In [ ]:
add_arr = arr1+arr2 # adding numpy arrays leads to elements-wise addition
add_arr

array([ 7,  9, 11, 13, 15])

In [ ]:
sub_arr = arr1 - arr2 # does element-wise subtraction and is true for other operations as well
sub_arr

array([-5, -5, -5, -5, -5])